[tool.pytest.ini_options]
minversion = "6.0"

addopts = "-ra -q --strict-markers --import-mode=importlib"

# Pointing to your specific testbench folders
pythonpath = [
    ".",
]
testpaths = [
    "multiplier_demo/tb",
    "median_filter/tb",
]

python_files = ["*_runner.py"]

# Register custom markers
markers = [
    "slow: marks tests as slow",
    "hardware: marks tests that require hardware",
]

log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s"
log_cli_date_format = "%H:%M:%S"
