name: ieee_chip_team
channels:
  - defaults
  - conda-forge
  - vlsida-eda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - colorama=0.4.6
  - dav1d=1.2.1
  - exceptiongroup=1.3.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - iniconfig=2.3.0
  - jpeg=9f
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libavif=1.3.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.84.4
  - libgomp=15.2.0
  - libiconv=1.16
  - libnsl=2.0.0
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - ncurses=6.5
  - openssl=3.6.1
  - packaging=26.0
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pluggy=1.6.0
  - pthread-stubs=0.3
  - pygments=2.19.2
  - pytest=9.0.2
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tomli=2.4.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - cocotb==2.0.1
      - find-libpython==0.5.0
prefix: /home/dcc3637/miniconda3/envs/ieee_chip_team
